//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace J.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        public material()
        {
            this.designworks = new HashSet<designwork>();
            this.materialcolors = new HashSet<materialcolor>();
            this.materialpictures = new HashSet<materialpicture>();
            this.materialpricelogs = new HashSet<materialpricelog>();
            this.materialsizes = new HashSet<materialsize>();
        }
    
        public string GUID { get; set; }
        public string TypeID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int PictureNumber { get; set; }
        public int State { get; set; }
    
        public virtual ICollection<designwork> designworks { get; set; }
        public virtual ICollection<materialcolor> materialcolors { get; set; }
        public virtual ICollection<materialpicture> materialpictures { get; set; }
        public virtual ICollection<materialpricelog> materialpricelogs { get; set; }
        public virtual materialtype materialtype { get; set; }
        public virtual ICollection<materialsize> materialsizes { get; set; }
    }
}
