//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace J.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.addresses = new HashSet<address>();
            this.designworks = new HashSet<designwork>();
            this.orders = new HashSet<order>();
            this.singlelogins = new HashSet<singlelogin>();
        }
    
        public string GUID { get; set; }
        public string RealName { get; set; }
        public string Email { get; set; }
        public string StageName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int State { get; set; }
    
        public virtual ICollection<address> addresses { get; set; }
        public virtual ICollection<designwork> designworks { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<singlelogin> singlelogins { get; set; }
    }
}
